import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {handlePdfDownload} from '../server/worker.mjs';

const read = file => readFileSync(new URL('../dist/' + file, import.meta.url), 'utf8');
const context = vm.createContext({Blob});
vm.runInContext(read('catalog.js') + '\n' + read('photo.js') + '\n' + read('pdf.js') + '\nthis.api={templates,resumePdfDefinition,resumePdfFilename,createResumePdfBlob,folioPdfFonts};', context);
const {templates,resumePdfDefinition,resumePdfFilename,createResumePdfBlob,folioPdfFonts} = context.api;
const data = {name: 'Taylor Example', role: 'Research Engineer', email: 'hello@example.com', phone: '', location: 'Example City', website: 'example.com', summary: 'PROFILE_SENTINEL', experience: [{title: 'ROLE_SENTINEL', company: 'COMPANY_SENTINEL', dates: '2022–2026', details: 'WORK_SENTINEL\nSECOND_BULLET'}], education: [{degree: 'DEGREE_SENTINEL', school: 'SCHOOL_SENTINEL', dates: '2018–2022', details: 'EDUCATION_SENTINEL'}], skills: 'SKILL_SENTINEL, JavaScript', projects: [{title: 'PROJECT_SENTINEL', link: 'example.com/project', details: 'PROJECT_DETAIL'}], extraTitle: 'Languages', extra: 'English, Hindi'};

test('all 63 PDF templates retain every section and entry exactly once', () => {
 for (const template of templates) {
  const doc = resumePdfDefinition(data, template.id, '#123456');
  const content = JSON.stringify(doc.content);
  for (const value of ['PROFILE_SENTINEL','ROLE_SENTINEL','COMPANY_SENTINEL','WORK_SENTINEL','SECOND_BULLET','DEGREE_SENTINEL','SCHOOL_SENTINEL','EDUCATION_SENTINEL','SKILL_SENTINEL','PROJECT_SENTINEL','PROJECT_DETAIL','English, Hindi']) assert.equal(content.split(value).length - 1, 1, `${template.id}: ${value}`);
  assert.equal(doc.pageSize, 'A4');
  assert.equal(doc.info.subject, template.name);
  assert(content.includes('#123456'));
 }
});

test('PDF paper sizes, safe filenames, fonts, and empty optional sections', () => {
 assert.equal(resumePdfDefinition(data,'everyday','#294c40','Letter').pageSize,'LETTER');
 assert.equal(resumePdfDefinition(data,'scholar','#294c40').defaultStyle.font,'Serif');
 assert.equal(resumePdfFilename('../Taylor: Example/','atlas'),'Taylor-Example-atlas-resume.pdf');
 for (const t of templates) {
  const doc = resumePdfDefinition({...data,summary:'',experience:[],education:[],projects:[],skills:'',extra:''},t.id,t.color);
  assert(!JSON.stringify(doc.content).includes('EXPERIENCE'));
 }
});

function commonJs(source) {
 const module = {exports: {}};
 vm.runInThisContext('(function(module,exports){' + source + '\n})')(module, module.exports);
 return module.exports;
}
const engine = commonJs(read('vendor/pdfmake.min.js'));
const vfs = commonJs(read('vendor/folio-fonts.js'));
engine.addVirtualFileSystem(vfs);

test('the bundled engine generates actual PDF files for all eight layouts, contact bands, and both sizes', async () => {
 for (const id of ['momentum','atlas','orbit','prism','contour','scholar','byte','anchor','mosaic','milestone','brief','broadcast']) {
  for (const size of ['A4','Letter']) {
   const blob = await createResumePdfBlob(engine,resumePdfDefinition(data,id,'#365cc5',size));
   const bytes = Buffer.from(await blob.arrayBuffer());
   assert.equal(blob.type,'application/pdf');
   assert(bytes.subarray(0,8).toString().startsWith('%PDF-1.'));
   assert(bytes.subarray(-20).toString().includes('%%EOF'));
  }
 }
});

test('generation errors reject instead of leaving the download waiting forever', async () => {
 await assert.rejects(createResumePdfBlob({createPdf(){throw new Error('unavailable');}},{}),/unavailable/);
});

test('photo templates embed uploaded pictures in real PDFs and omit them from text-only styles', async () => {
 const photo='data:image/jpeg;base64,'+readFileSync(new URL('../assets/demo-profile-portrait.jpg',import.meta.url)).toString('base64');
 for(const t of templates.filter(t=>t.photo)){
  const doc=resumePdfDefinition(data,t.id,t.color,'A4',photo);
  assert(JSON.stringify(doc.content).includes(photo),t.id);
  const blob=await createResumePdfBlob(engine,doc);
  assert(Buffer.from(await blob.arrayBuffer()).toString('latin1').includes('/Subtype /Image'),t.id);
 }
 assert(!JSON.stringify(resumePdfDefinition(data,'atlas','#345f54','A4',photo)).includes(photo));
 assert(!JSON.stringify(resumePdfDefinition(data,'portrait','#345f54','A4','https://example.com/face.png')).includes('https://example.com/face.png'));
});

test('download endpoint returns the generated bytes with PDF attachment headers', async () => {
 const blob = await createResumePdfBlob(engine,resumePdfDefinition(data,'momentum','#365cc5'));
 const bytes = Buffer.from(await blob.arrayBuffer());
 const response = await handlePdfDownload(new Request('https://folio.example/api/pdf-download',{
  method:'POST', headers:{Origin:'https://folio.example'},
  body:new URLSearchParams({pdf:bytes.toString('base64'),filename:'Taylor-Example-resume.pdf'})
 }));
 assert.equal(response.status,200);
 assert.equal(response.headers.get('content-type'),'application/pdf');
 assert.match(response.headers.get('content-disposition'),/^attachment; filename="Taylor-Example-resume.pdf"/);
 assert.equal(response.headers.get('cache-control'),'no-store');
 assert.deepEqual(Buffer.from(await response.arrayBuffer()),bytes);
});

test('download endpoint rejects foreign origins, invalid files, and oversized bodies', async () => {
 const req = (pdf,origin='https://folio.example') => new Request('https://folio.example/api/pdf-download',{method:'POST',headers:{Origin:origin},body:new URLSearchParams({pdf,filename:'resume.pdf'})});
 assert.equal((await handlePdfDownload(req('bad','https://other.example'))).status,403);
 assert.equal((await handlePdfDownload(req(Buffer.from('<script>bad</script>').toString('base64')))).status,400);
 assert.equal((await handlePdfDownload(req('!invalid'))).status,400);
 assert.equal((await handlePdfDownload(req('A'.repeat(2*1024*1024)))).status,413);
 assert.equal((await handlePdfDownload(new Request('https://folio.example/api/pdf-download'))).status,405);
});
