import test from 'node:test';
import assert from 'node:assert/strict';
import {handleExtraction,validateResume} from '../server/worker.mjs';
const empty={name:'Jordan Lee',role:'Developer',email:'jordan@example.com',phone:'',location:'',website:'',summary:'',skills:'JavaScript',extraTitle:'',extra:'',experience:[],education:[],projects:[]};
let requestNumber=0;
function req(body={text:'Jordan Lee is a developer. Skills include JavaScript and HTML.'},extra={}){return new Request('https://folio-resume-studio.connect350599.chatgpt.site/api/extract',{method:'POST',headers:{Origin:'https://folio-resume-studio.connect350599.chatgpt.site','Content-Type':'application/json','CF-Connecting-IP':String(++requestNumber),...extra},body:JSON.stringify(body)})}
const env={GEMINI_API_KEY:'test-only-secret',GEMINI_MODEL:'gemini-3.1-flash-lite'};
test('extracts structured data and keeps API key in the upstream header only',async()=>{let seen;const result=await handleExtraction(req(),env,async(url,options)=>{seen={url,options};return Response.json({candidates:[{finishReason:'STOP',content:{parts:[{text:JSON.stringify(empty)}]}}]})});assert.equal(result.status,200);assert.deepEqual((await result.json()).data,empty);assert.equal(seen.options.headers['x-goog-api-key'],env.GEMINI_API_KEY);assert(!seen.url.includes(env.GEMINI_API_KEY));assert(!seen.options.body.includes(env.GEMINI_API_KEY));const config=JSON.parse(seen.options.body);assert.equal(config.generationConfig.responseMimeType,'application/json');assert(config.generationConfig.responseJsonSchema.required.includes('education'))});
test('blocks cross-origin requests before contacting Gemini',async()=>{let contacted=false;const result=await handleExtraction(req(undefined,{Origin:'https://other.example'}),env,async()=>{contacted=true});assert.equal(result.status,403);assert.equal(contacted,false)});
test('rejects short, oversized, and non-string source text',async()=>{for(const text of ['short','x'.repeat(16001),null]){const result=await handleExtraction(req({text}),env);assert.equal(result.status,400)}});
test('caps actual request body bytes',async()=>{const result=await handleExtraction(req({text:'🟢'.repeat(17000)}),env);assert.equal(result.status,413)});
test('reports configuration and quota failures without exposing upstream details',async()=>{assert.equal((await handleExtraction(req(),{})).status,503);const result=await handleExtraction(req(),env,async()=>new Response('sensitive upstream detail',{status:429}));assert.equal(result.status,429);assert(!(await result.text()).includes('sensitive upstream detail'))});
test('rejects malformed, empty, and interrupted AI results',async()=>{for(const payload of [{candidates:[{finishReason:'MAX_TOKENS'}]},{candidates:[{finishReason:'STOP',content:{parts:[{text:'not json'}]}}]},{candidates:[{finishReason:'STOP',content:{parts:[{text:JSON.stringify({...empty,name:'',role:'',skills:''})}]}}]}]){assert.equal((await handleExtraction(req(),env,async()=>Response.json(payload))).status,422)}});
test('normalizes known fields only and rejects wrong entry types',()=>{const result=validateResume({...empty,unexpected:'ignored',experience:[{title:' Engineer ',company:'Example',dates:'2024',details:'Built a tool.'}]});assert.equal(result.experience[0].title,'Engineer');assert(!('unexpected'in result));assert.throws(()=>validateResume({...empty,experience:[{title:42}]}))});
test('times out safely without overwriting any browser state',async()=>{const result=await handleExtraction(req(),env,async()=>{throw Object.assign(new Error('timeout'),{name:'TimeoutError'})});assert.equal(result.status,504);assert.match((await result.json()).error,/text is still here/)});
